###################################################################

# Created by write_sdc on Wed Feb 17 01:16:59 2021

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_load -pin_load 3.40189 [get_ports {pc[63]}]
set_load -pin_load 3.40189 [get_ports {pc[62]}]
set_load -pin_load 3.40189 [get_ports {pc[61]}]
set_load -pin_load 3.40189 [get_ports {pc[60]}]
set_load -pin_load 3.40189 [get_ports {pc[59]}]
set_load -pin_load 3.40189 [get_ports {pc[58]}]
set_load -pin_load 3.40189 [get_ports {pc[57]}]
set_load -pin_load 3.40189 [get_ports {pc[56]}]
set_load -pin_load 3.40189 [get_ports {pc[55]}]
set_load -pin_load 3.40189 [get_ports {pc[54]}]
set_load -pin_load 3.40189 [get_ports {pc[53]}]
set_load -pin_load 3.40189 [get_ports {pc[52]}]
set_load -pin_load 3.40189 [get_ports {pc[51]}]
set_load -pin_load 3.40189 [get_ports {pc[50]}]
set_load -pin_load 3.40189 [get_ports {pc[49]}]
set_load -pin_load 3.40189 [get_ports {pc[48]}]
set_load -pin_load 3.40189 [get_ports {pc[47]}]
set_load -pin_load 3.40189 [get_ports {pc[46]}]
set_load -pin_load 3.40189 [get_ports {pc[45]}]
set_load -pin_load 3.40189 [get_ports {pc[44]}]
set_load -pin_load 3.40189 [get_ports {pc[43]}]
set_load -pin_load 3.40189 [get_ports {pc[42]}]
set_load -pin_load 3.40189 [get_ports {pc[41]}]
set_load -pin_load 3.40189 [get_ports {pc[40]}]
set_load -pin_load 3.40189 [get_ports {pc[39]}]
set_load -pin_load 3.40189 [get_ports {pc[38]}]
set_load -pin_load 3.40189 [get_ports {pc[37]}]
set_load -pin_load 3.40189 [get_ports {pc[36]}]
set_load -pin_load 3.40189 [get_ports {pc[35]}]
set_load -pin_load 3.40189 [get_ports {pc[34]}]
set_load -pin_load 3.40189 [get_ports {pc[33]}]
set_load -pin_load 3.40189 [get_ports {pc[32]}]
set_load -pin_load 3.40189 [get_ports {pc[31]}]
set_load -pin_load 3.40189 [get_ports {pc[30]}]
set_load -pin_load 3.40189 [get_ports {pc[29]}]
set_load -pin_load 3.40189 [get_ports {pc[28]}]
set_load -pin_load 3.40189 [get_ports {pc[27]}]
set_load -pin_load 3.40189 [get_ports {pc[26]}]
set_load -pin_load 3.40189 [get_ports {pc[25]}]
set_load -pin_load 3.40189 [get_ports {pc[24]}]
set_load -pin_load 3.40189 [get_ports {pc[23]}]
set_load -pin_load 3.40189 [get_ports {pc[22]}]
set_load -pin_load 3.40189 [get_ports {pc[21]}]
set_load -pin_load 3.40189 [get_ports {pc[20]}]
set_load -pin_load 3.40189 [get_ports {pc[19]}]
set_load -pin_load 3.40189 [get_ports {pc[18]}]
set_load -pin_load 3.40189 [get_ports {pc[17]}]
set_load -pin_load 3.40189 [get_ports {pc[16]}]
set_load -pin_load 3.40189 [get_ports {pc[15]}]
set_load -pin_load 3.40189 [get_ports {pc[14]}]
set_load -pin_load 3.40189 [get_ports {pc[13]}]
set_load -pin_load 3.40189 [get_ports {pc[12]}]
set_load -pin_load 3.40189 [get_ports {pc[11]}]
set_load -pin_load 3.40189 [get_ports {pc[10]}]
set_load -pin_load 3.40189 [get_ports {pc[9]}]
set_load -pin_load 3.40189 [get_ports {pc[8]}]
set_load -pin_load 3.40189 [get_ports {pc[7]}]
set_load -pin_load 3.40189 [get_ports {pc[6]}]
set_load -pin_load 3.40189 [get_ports {pc[5]}]
set_load -pin_load 3.40189 [get_ports {pc[4]}]
set_load -pin_load 3.40189 [get_ports {pc[3]}]
set_load -pin_load 3.40189 [get_ports {pc[2]}]
set_load -pin_load 3.40189 [get_ports {pc[1]}]
set_load -pin_load 3.40189 [get_ports {pc[0]}]
set_load -pin_load 3.40189 [get_ports {address[63]}]
set_load -pin_load 3.40189 [get_ports {address[62]}]
set_load -pin_load 3.40189 [get_ports {address[61]}]
set_load -pin_load 3.40189 [get_ports {address[60]}]
set_load -pin_load 3.40189 [get_ports {address[59]}]
set_load -pin_load 3.40189 [get_ports {address[58]}]
set_load -pin_load 3.40189 [get_ports {address[57]}]
set_load -pin_load 3.40189 [get_ports {address[56]}]
set_load -pin_load 3.40189 [get_ports {address[55]}]
set_load -pin_load 3.40189 [get_ports {address[54]}]
set_load -pin_load 3.40189 [get_ports {address[53]}]
set_load -pin_load 3.40189 [get_ports {address[52]}]
set_load -pin_load 3.40189 [get_ports {address[51]}]
set_load -pin_load 3.40189 [get_ports {address[50]}]
set_load -pin_load 3.40189 [get_ports {address[49]}]
set_load -pin_load 3.40189 [get_ports {address[48]}]
set_load -pin_load 3.40189 [get_ports {address[47]}]
set_load -pin_load 3.40189 [get_ports {address[46]}]
set_load -pin_load 3.40189 [get_ports {address[45]}]
set_load -pin_load 3.40189 [get_ports {address[44]}]
set_load -pin_load 3.40189 [get_ports {address[43]}]
set_load -pin_load 3.40189 [get_ports {address[42]}]
set_load -pin_load 3.40189 [get_ports {address[41]}]
set_load -pin_load 3.40189 [get_ports {address[40]}]
set_load -pin_load 3.40189 [get_ports {address[39]}]
set_load -pin_load 3.40189 [get_ports {address[38]}]
set_load -pin_load 3.40189 [get_ports {address[37]}]
set_load -pin_load 3.40189 [get_ports {address[36]}]
set_load -pin_load 3.40189 [get_ports {address[35]}]
set_load -pin_load 3.40189 [get_ports {address[34]}]
set_load -pin_load 3.40189 [get_ports {address[33]}]
set_load -pin_load 3.40189 [get_ports {address[32]}]
set_load -pin_load 3.40189 [get_ports {address[31]}]
set_load -pin_load 3.40189 [get_ports {address[30]}]
set_load -pin_load 3.40189 [get_ports {address[29]}]
set_load -pin_load 3.40189 [get_ports {address[28]}]
set_load -pin_load 3.40189 [get_ports {address[27]}]
set_load -pin_load 3.40189 [get_ports {address[26]}]
set_load -pin_load 3.40189 [get_ports {address[25]}]
set_load -pin_load 3.40189 [get_ports {address[24]}]
set_load -pin_load 3.40189 [get_ports {address[23]}]
set_load -pin_load 3.40189 [get_ports {address[22]}]
set_load -pin_load 3.40189 [get_ports {address[21]}]
set_load -pin_load 3.40189 [get_ports {address[20]}]
set_load -pin_load 3.40189 [get_ports {address[19]}]
set_load -pin_load 3.40189 [get_ports {address[18]}]
set_load -pin_load 3.40189 [get_ports {address[17]}]
set_load -pin_load 3.40189 [get_ports {address[16]}]
set_load -pin_load 3.40189 [get_ports {address[15]}]
set_load -pin_load 3.40189 [get_ports {address[14]}]
set_load -pin_load 3.40189 [get_ports {address[13]}]
set_load -pin_load 3.40189 [get_ports {address[12]}]
set_load -pin_load 3.40189 [get_ports {address[11]}]
set_load -pin_load 3.40189 [get_ports {address[10]}]
set_load -pin_load 3.40189 [get_ports {address[9]}]
set_load -pin_load 3.40189 [get_ports {address[8]}]
set_load -pin_load 3.40189 [get_ports {address[7]}]
set_load -pin_load 3.40189 [get_ports {address[6]}]
set_load -pin_load 3.40189 [get_ports {address[5]}]
set_load -pin_load 3.40189 [get_ports {address[4]}]
set_load -pin_load 3.40189 [get_ports {address[3]}]
set_load -pin_load 3.40189 [get_ports {address[2]}]
set_load -pin_load 3.40189 [get_ports {address[1]}]
set_load -pin_load 3.40189 [get_ports {address[0]}]
set_load -pin_load 3.40189 [get_ports {write_data[63]}]
set_load -pin_load 3.40189 [get_ports {write_data[62]}]
set_load -pin_load 3.40189 [get_ports {write_data[61]}]
set_load -pin_load 3.40189 [get_ports {write_data[60]}]
set_load -pin_load 3.40189 [get_ports {write_data[59]}]
set_load -pin_load 3.40189 [get_ports {write_data[58]}]
set_load -pin_load 3.40189 [get_ports {write_data[57]}]
set_load -pin_load 3.40189 [get_ports {write_data[56]}]
set_load -pin_load 3.40189 [get_ports {write_data[55]}]
set_load -pin_load 3.40189 [get_ports {write_data[54]}]
set_load -pin_load 3.40189 [get_ports {write_data[53]}]
set_load -pin_load 3.40189 [get_ports {write_data[52]}]
set_load -pin_load 3.40189 [get_ports {write_data[51]}]
set_load -pin_load 3.40189 [get_ports {write_data[50]}]
set_load -pin_load 3.40189 [get_ports {write_data[49]}]
set_load -pin_load 3.40189 [get_ports {write_data[48]}]
set_load -pin_load 3.40189 [get_ports {write_data[47]}]
set_load -pin_load 3.40189 [get_ports {write_data[46]}]
set_load -pin_load 3.40189 [get_ports {write_data[45]}]
set_load -pin_load 3.40189 [get_ports {write_data[44]}]
set_load -pin_load 3.40189 [get_ports {write_data[43]}]
set_load -pin_load 3.40189 [get_ports {write_data[42]}]
set_load -pin_load 3.40189 [get_ports {write_data[41]}]
set_load -pin_load 3.40189 [get_ports {write_data[40]}]
set_load -pin_load 3.40189 [get_ports {write_data[39]}]
set_load -pin_load 3.40189 [get_ports {write_data[38]}]
set_load -pin_load 3.40189 [get_ports {write_data[37]}]
set_load -pin_load 3.40189 [get_ports {write_data[36]}]
set_load -pin_load 3.40189 [get_ports {write_data[35]}]
set_load -pin_load 3.40189 [get_ports {write_data[34]}]
set_load -pin_load 3.40189 [get_ports {write_data[33]}]
set_load -pin_load 3.40189 [get_ports {write_data[32]}]
set_load -pin_load 3.40189 [get_ports {write_data[31]}]
set_load -pin_load 3.40189 [get_ports {write_data[30]}]
set_load -pin_load 3.40189 [get_ports {write_data[29]}]
set_load -pin_load 3.40189 [get_ports {write_data[28]}]
set_load -pin_load 3.40189 [get_ports {write_data[27]}]
set_load -pin_load 3.40189 [get_ports {write_data[26]}]
set_load -pin_load 3.40189 [get_ports {write_data[25]}]
set_load -pin_load 3.40189 [get_ports {write_data[24]}]
set_load -pin_load 3.40189 [get_ports {write_data[23]}]
set_load -pin_load 3.40189 [get_ports {write_data[22]}]
set_load -pin_load 3.40189 [get_ports {write_data[21]}]
set_load -pin_load 3.40189 [get_ports {write_data[20]}]
set_load -pin_load 3.40189 [get_ports {write_data[19]}]
set_load -pin_load 3.40189 [get_ports {write_data[18]}]
set_load -pin_load 3.40189 [get_ports {write_data[17]}]
set_load -pin_load 3.40189 [get_ports {write_data[16]}]
set_load -pin_load 3.40189 [get_ports {write_data[15]}]
set_load -pin_load 3.40189 [get_ports {write_data[14]}]
set_load -pin_load 3.40189 [get_ports {write_data[13]}]
set_load -pin_load 3.40189 [get_ports {write_data[12]}]
set_load -pin_load 3.40189 [get_ports {write_data[11]}]
set_load -pin_load 3.40189 [get_ports {write_data[10]}]
set_load -pin_load 3.40189 [get_ports {write_data[9]}]
set_load -pin_load 3.40189 [get_ports {write_data[8]}]
set_load -pin_load 3.40189 [get_ports {write_data[7]}]
set_load -pin_load 3.40189 [get_ports {write_data[6]}]
set_load -pin_load 3.40189 [get_ports {write_data[5]}]
set_load -pin_load 3.40189 [get_ports {write_data[4]}]
set_load -pin_load 3.40189 [get_ports {write_data[3]}]
set_load -pin_load 3.40189 [get_ports {write_data[2]}]
set_load -pin_load 3.40189 [get_ports {write_data[1]}]
set_load -pin_load 3.40189 [get_ports {write_data[0]}]
set_load -pin_load 3.40189 [get_ports data_mem_read]
set_load -pin_load 3.40189 [get_ports data_mem_write]
create_clock [get_ports clk]  -name MY_CLK  -period 3  -waveform {0 1.5}
set_clock_uncertainty 0.07  [get_clocks MY_CLK]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports rst_n]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[31]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[30]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[29]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[28]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[27]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[26]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[25]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[24]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[23]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[22]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[21]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[20]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[19]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[18]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[17]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[16]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[15]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[14]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[13]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {istruction[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[63]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[62]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[61]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[60]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[59]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[58]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[57]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[56]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[55]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[54]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[53]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[52]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[51]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[50]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[49]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[48]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[47]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[46]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[45]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[44]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[43]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[42]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[41]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[40]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[39]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[38]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[37]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[36]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[35]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[34]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[33]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[32]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[31]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[30]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[29]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[28]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[27]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[26]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[25]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[24]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[23]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[22]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[21]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[20]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[19]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[18]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[17]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[16]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[15]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[14]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[13]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {data_mem[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[63]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[62]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[61]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[60]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[59]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[58]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[57]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[56]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[55]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[54]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[53]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[52]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[51]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[50]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[49]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[48]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[47]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[46]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[45]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[44]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[43]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[42]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[41]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[40]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[39]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[38]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[37]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[36]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[35]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[34]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[33]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[32]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[31]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[30]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[29]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[28]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[27]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[26]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[25]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[24]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[23]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[22]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[21]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[20]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[19]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[18]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[17]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[16]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[15]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[14]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[13]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {pc[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[63]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[62]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[61]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[60]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[59]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[58]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[57]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[56]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[55]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[54]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[53]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[52]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[51]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[50]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[49]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[48]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[47]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[46]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[45]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[44]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[43]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[42]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[41]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[40]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[39]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[38]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[37]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[36]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[35]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[34]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[33]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[32]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[31]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[30]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[29]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[28]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[27]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[26]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[25]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[24]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[23]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[22]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[21]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[20]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[19]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[18]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[17]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[16]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[15]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[14]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[13]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[63]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[62]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[61]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[60]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[59]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[58]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[57]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[56]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[55]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[54]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[53]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[52]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[51]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[50]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[49]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[48]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[47]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[46]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[45]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[44]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[43]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[42]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[41]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[40]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[39]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[38]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[37]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[36]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[35]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[34]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[33]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[32]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[31]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[30]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[29]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[28]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[27]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[26]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[25]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[24]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[23]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[22]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[21]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[20]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[19]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[18]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[17]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[16]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[15]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[14]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[13]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports data_mem_read]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports data_mem_write]
